import sys, os, time
import numpy as np
from synth import *
import sfx

names = sys.argv[1:] or list(sfx.SOUNDS.keys())
t0 = time.time()
for n in names:
    x = sfx.SOUNDS[n]()
    x = np.nan_to_num(x)
    write_wav(x, os.path.join(sfx.OUT, n + ".wav"))
print("rendered %d sounds in %.1f s" % (len(names), time.time() - t0))

# the lists that the game reads (generated)
path = os.path.join(os.path.dirname(__file__), "..", "..", "game", "scripts", "systems", "audio_names.gd")
sfx_list = "[" + ", ".join('"%s"' % n for n in sorted(sfx.SOUNDS.keys())) + "]"
music_list = '["title", "boardwalk", "beach", "hill", "sea", "summit", "sky", "star", "ending", "cine_joy", "cine_wish", "cine_home"]'
with open(path, "w") as f:
    f.write("# GENERATED by tools/audio/render_sfx.py - do not edit\n")
    f.write("const SFX = %s\n" % sfx_list)
    f.write("const MUSIC = %s\n" % music_list)
